apiVersion: apps/v1
kind: Deployment
metadata:
  name: achenlab28
  labels:
    app: achenwebnginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: achennginxwebpod
  template:
    metadata:
      labels:
        app: achennginxwebpod
    spec:
      containers:
      - name: nginx
        image: alexchen2015/lab28:1.0.0
        imagePullPolicy: Always 
---
apiVersion: v1 
kind: Service 
metadata: 
    name: achenlab28 
spec: 
   selector: 
     app: achennginxwebpod 
   type: NodePort
   ports: 
        - protocol: TCP 
          port: 80 
          targetPort: 80 
